// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// udp_logger
void udp_logger(std::string path);
RcppExport SEXP _tempestwx_udp_logger(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    udp_logger(path);
    return R_NilValue;
END_RCPP
}
// udp_callback_logger
void udp_callback_logger(Function f);
RcppExport SEXP _tempestwx_udp_callback_logger(SEXP fSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    udp_callback_logger(f);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tempestwx_udp_logger", (DL_FUNC) &_tempestwx_udp_logger, 1},
    {"_tempestwx_udp_callback_logger", (DL_FUNC) &_tempestwx_udp_callback_logger, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_tempestwx(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
