# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Log local UDP Tempest messages to a file
#'
#' This dedicates the R session to logging UDP packets to a file. No other operations
#' can be performed until terminated.
#'
#' @param path full path (no expansion is performed) to a file
#' @references <https://weatherflow.github.io/Tempest/api/udp/v171/>
#' @return nothing!
#' @export
#' @examples
#' # udp_logger("/tmp/logger.json")
udp_logger <- function(path) {
    invisible(.Call(`_tempestwx_udp_logger`, path))
}

#' Log local UDP Tempest messages to a file
#'
#' This dedicates the R session to logging UDP packets to a file. No other operations
#' can be performed until terminated.
#'
#' @param f R function callback (one param: length 1 chr)
#' @references <https://weatherflow.github.io/Tempest/api/udp/v171/>
#' @return nothing!
#' @export
#' @examples
#' # udp_callback_logger(function(x) writeLines(x))
udp_callback_logger <- function(f) {
    invisible(.Call(`_tempestwx_udp_callback_logger`, f))
}

